/*
 * Copyright 2026 Spice Labs, Inc.
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */
package io.spicelabs.saffron.corpus;

import java.util.List;

/**
 * Shared data classes for corpus verification tests.
 *
 * <p>These classes map directly to the JSON ground truth files generated by
 * the Docker corpus scanner (tools/corpus-scanner/). They are used by all
 * corpus verification test classes.
 */
final class CorpusTestData {

    private CorpusTestData() {}

    static class CorpusImageData {
        String imagePath;
        String imageBasename;
        int filesystemCount;
        int totalFiles;
        int totalDirectories;
        List<FilesystemData> filesystems;
        String error;

        /** Returns the fstype of the first filesystem, or null. */
        String firstFilesystemType() {
            if (filesystems != null && !filesystems.isEmpty()) {
                return filesystems.get(0).fstype;
            }
            return null;
        }
    }

    static class FilesystemData {
        String device;
        String fstype;
        int fileCount;
        int directoryCount;
        List<SampleFile> sampleFiles;
    }

    static class SampleFile {
        String path;
        String sha256;
        long size;
    }
}
