/*
 * Copyright 2026 Spice Labs, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */
package io.spicelabs.saffron.corpus;

import com.google.gson.Gson;
import io.spicelabs.saffron.DiskReader;
import io.spicelabs.saffron.VirtualDisk;
import io.spicelabs.saffron.fs.FileSystem;
import io.spicelabs.saffron.fs.FileSystemEntry;
import io.spicelabs.saffron.fs.FileSystemMount;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.condition.EnabledIf;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertTimeoutPreemptively;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Full corpus verification test - validates Saffron against ground truth data
 * generated by external filesystem tools (libguestfs in Docker).
 *
 * <p><b>CRITICAL INVARIANTS (zero tolerance):</b>
 * <ul>
 *   <li>Filesystem count must match exactly</li>
 *   <li>Total file count across all filesystems must match exactly (not even ±1)</li>
 *   <li>All sample files must be findable with correct SHA256 and size</li>
 * </ul>
 *
 * <p>The JSON verification files in src/test/resources/corpus-verification/ are
 * GROUND TRUTH generated by EXTERNAL filesystem tools (real OS mount + real tools),
 * NOT by Saffron code. Any discrepancy is a Saffron bug.
 */
@Execution(ExecutionMode.CONCURRENT)
class CorpusFullVerificationTest {

    private static final String CORPUS_BASE = Path.of("test-corpus").toAbsolutePath().toString();
    private static final Path VERIFICATION_DIR = Path.of("src/test/resources/corpus-verification");
    private static final Gson GSON = new Gson();
    private static List<VerificationTestCase> testCases;

    // Track results for summary
    private static final List<String> passed = Collections.synchronizedList(new ArrayList<>());
    private static final List<String> failed = Collections.synchronizedList(new ArrayList<>());

    static boolean corpusExists() {
        return Files.isDirectory(Path.of(CORPUS_BASE));
    }

    @BeforeAll
    static void loadAllVerificationData() throws IOException {
        testCases = new ArrayList<>();

        if (!Files.isDirectory(VERIFICATION_DIR)) {
            return;
        }

        try (Stream<Path> files = Files.list(VERIFICATION_DIR)) {
            files.filter(p -> p.toString().endsWith(".json"))
                 .forEach(jsonPath -> {
                     try (InputStream is = Files.newInputStream(jsonPath)) {
                         CorpusTestData.CorpusImageData data = GSON.fromJson(new InputStreamReader(is), CorpusTestData.CorpusImageData.class);
                         if (data != null && data.imagePath != null) {
                             Path imagePath = resolveImagePath(data.imagePath);
                             if (imagePath != null && Files.exists(imagePath)) {
                                 testCases.add(new VerificationTestCase(
                                     jsonPath.getFileName().toString(),
                                     imagePath,
                                     data
                                 ));
                             }
                         }
                     } catch (Exception e) {
                         System.err.println("Failed to load: " + jsonPath + " - " + e.getMessage());
                     }
                 });
        }

        testCases.sort(Comparator.comparing(tc -> tc.data.imageBasename));
        System.out.println("Loaded " + testCases.size() + " verification test cases");
    }

    @AfterAll
    static void printSummary() {
        System.out.println("\n" + "=".repeat(70));
        System.out.println("CORPUS VERIFICATION SUMMARY");
        System.out.println("=".repeat(70));
        System.out.println("PASSED: " + passed.size() + " images");
        System.out.println("FAILED: " + failed.size() + " images");
        System.out.println("-".repeat(70));

        if (!failed.isEmpty()) {
            System.out.println("\nFailures:");
            failed.forEach(s -> System.out.println("  - " + s));
        }
        System.out.println("=".repeat(70));
    }

    @TestFactory
    @EnabledIf("corpusExists")
    Collection<DynamicTest> verifyAllCorpusImages() {
        List<DynamicTest> tests = new ArrayList<>();

        for (VerificationTestCase tc : testCases) {
            // Skip images that had errors during ground truth generation
            // or where the external tool found no filesystems (format unsupported by libguestfs)
            if (tc.data.error != null || tc.data.filesystemCount == 0) {
                continue;
            }

            tests.add(DynamicTest.dynamicTest(
                tc.data.imageBasename,
                () -> assertTimeoutPreemptively(Duration.ofSeconds(120),
                    () -> verifyImage(tc),
                    "Image verification timed out after 120s: " + tc.data.imageBasename)
            ));
        }

        return tests;
    }

    private void verifyImage(VerificationTestCase tc) throws Exception {
        String name = tc.data.imageBasename;
        System.out.println("\n=== Verifying: " + name + " ===");

        try (VirtualDisk disk = DiskReader.open(tc.imagePath)) {
            // Mount ALL filesystems (partition + LVM) and get detected but unmountable filesystems (swap)
            FileSystemMount.MountAllResult mountResult = FileSystemMount.mountAllWithDetected(disk);
            List<FileSystem> allFs = mountResult.mounted();

            try {
                // ============================================================
                // INVARIANT 1: Filesystem count must match exactly
                // Includes both mounted filesystems and detected but unmountable (swap)
                // ============================================================
                int totalFilesystemCount = mountResult.totalFilesystemCount();
                assertThat(totalFilesystemCount)
                    .as("Filesystem count for " + name +
                        " must match external tools exactly (mounted: " + allFs.size() +
                        ", detected: " + mountResult.detected().size() + ")")
                    .isEqualTo(tc.data.filesystemCount);

                // ============================================================
                // INVARIANT 2: Total file count must match exactly
                // ============================================================
                AtomicLong actualFiles = new AtomicLong(0);
                AtomicLong actualDirs = new AtomicLong(0);
                AtomicLong hiddenSystemFiles = new AtomicLong(0);

                for (FileSystem fs : allFs) {
                    // For FAT filesystems, track hidden+system files separately
                    if (fs instanceof FileSystem.Fat32FileSystem fatFs) {
                        try {
                            FileSystem.Fat32FileSystem.FatFileCounts counts = fatFs.fileCounts();
                            actualFiles.addAndGet(counts.totalFiles());
                            hiddenSystemFiles.addAndGet(counts.hiddenSystemFiles());
                        } catch (Exception e) {
                            // Fall back to walk
                            try (Stream<FileSystemEntry> walkStream = fs.walk()) {
                                walkStream.forEach(entry -> {
                                    if (entry instanceof FileSystemEntry.RegularFile) {
                                        actualFiles.incrementAndGet();
                                    }
                                });
                            }
                        }
                        // Count directories separately
                        try (Stream<FileSystemEntry> walkStream = fs.walk()) {
                            walkStream.forEach(entry -> {
                                if (entry instanceof FileSystemEntry.Directory) {
                                    actualDirs.incrementAndGet();
                                }
                            });
                        }
                    } else {
                        try (Stream<FileSystemEntry> walkStream = fs.walk()) {
                            walkStream.forEach(entry -> {
                                if (entry instanceof FileSystemEntry.RegularFile) {
                                    actualFiles.incrementAndGet();
                                } else if (entry instanceof FileSystemEntry.Directory) {
                                    actualDirs.incrementAndGet();
                                }
                            });
                        }
                    }
                }

                System.out.println("Expected: " + tc.data.totalFiles + " files, " +
                                   tc.data.totalDirectories + " dirs, " +
                                   tc.data.filesystemCount + " filesystems");
                System.out.println("Actual:   " + actualFiles.get() + " files (" + hiddenSystemFiles.get() + " hidden+system), " +
                                   actualDirs.get() + " dirs, " +
                                   totalFilesystemCount + " filesystems (" +
                                   allFs.size() + " mounted, " +
                                   mountResult.detected().size() + " detected)");

                // For FAT filesystems, try total first, then check if expected is within range
                long expectedFiles = tc.data.totalFiles;
                long visibleFiles = actualFiles.get() - hiddenSystemFiles.get();

                if (actualFiles.get() == expectedFiles) {
                    // Perfect match - all files accounted for
                    System.out.println("File count matches exactly");
                } else if (hiddenSystemFiles.get() > 0 &&
                           visibleFiles <= expectedFiles &&
                           actualFiles.get() >= expectedFiles) {
                    // FAT filesystems: libguestfs excludes some but not all hidden+system files
                    // The expected count should fall between visible and total
                    System.out.println("File count matches for FAT filesystem (expected within visible..total range)");
                } else {
                    // Neither total nor visible matches - this is a real discrepancy
                    assertThat(actualFiles.get())
                        .as("Total file count for " + name +
                            " must match external tools exactly (expected " +
                            tc.data.totalFiles + ", got " + actualFiles.get() + ", " +
                            hiddenSystemFiles.get() + " hidden+system files, " +
                            visibleFiles + " visible files)")
                        .isEqualTo(tc.data.totalFiles);
                }

                // ============================================================
                // INVARIANT 3: All sample files must be findable with correct SHA256
                // ============================================================
                if (tc.data.filesystems != null) {
                    List<String> errors = new ArrayList<>();

                    for (CorpusTestData.FilesystemData fsData : tc.data.filesystems) {
                        if (fsData.sampleFiles == null) continue;

                        for (CorpusTestData.SampleFile sample : fsData.sampleFiles) {
                            // Try resolving across all mounted filesystems.
                            // Prefer the one whose size matches the expected size (handles
                            // ambiguous paths that exist on multiple filesystems).
                            FileSystemEntry.RegularFile file = null;
                            for (FileSystem fs : allFs) {
                                var entry = fs.resolve(sample.path);
                                if (entry.isPresent() && entry.get() instanceof FileSystemEntry.RegularFile rf) {
                                    if (file == null) {
                                        file = rf;
                                    }
                                    if (rf.size() == sample.size) {
                                        file = rf;
                                        break;
                                    }
                                }
                            }

                            if (file == null) {
                                errors.add("File not found: " + sample.path);
                                continue;
                            }

                            byte[] content;
                            try (InputStream in = file.openStream()) {
                                content = in.readAllBytes();
                            }

                            if (content.length != sample.size) {
                                errors.add("Size mismatch for " + sample.path +
                                    ": expected " + sample.size + ", got " + content.length);
                            }

                            String actualSha256 = sha256(content);
                            if (!actualSha256.equalsIgnoreCase(sample.sha256)) {
                                errors.add("SHA256 mismatch for " + sample.path +
                                    ": expected " + sample.sha256.substring(0, 16) + "..." +
                                    ", got " + actualSha256.substring(0, 16) + "...");
                            }
                        }
                    }

                    if (!errors.isEmpty()) {
                        failed.add(name + " - " + errors.size() + " sample file errors");
                        fail("Sample file verification failed for " + name + ":\n  " +
                             String.join("\n  ", errors));
                    }
                }

                passed.add(name + " (" + actualFiles.get() + " files, " + allFs.size() + " fs)");
                System.out.println("PASSED");

            } finally {
                for (FileSystem fs : allFs) {
                    try { fs.close(); } catch (Exception ignored) {}
                }
            }
        } catch (AssertionError e) {
            if (!failed.stream().anyMatch(s -> s.startsWith(name))) {
                failed.add(name + " - " + e.getMessage());
            }
            throw e;
        } catch (Exception e) {
            failed.add(name + " - " + e.getClass().getSimpleName() + ": " + e.getMessage());
            throw e;
        }
    }

    private static Path resolveImagePath(String containerPath) {
        if (containerPath != null && containerPath.startsWith("/corpus/")) {
            String relativePath = containerPath.substring("/corpus/".length());
            return Path.of(CORPUS_BASE, relativePath);
        }
        return null;
    }

    private String sha256(byte[] data) throws Exception {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(data);
        return HexFormat.of().formatHex(hash);
    }

    record VerificationTestCase(String jsonFile, Path imagePath, CorpusTestData.CorpusImageData data) {}
}
