/*
 * Copyright 2026 Spice Labs, Inc.
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */
package io.spicelabs.saffron.corpus;

import com.google.gson.Gson;
import io.spicelabs.saffron.DiskReader;
import io.spicelabs.saffron.VirtualDisk;
import io.spicelabs.saffron.fs.FileSystem;
import io.spicelabs.saffron.fs.FileSystemEntry;
import io.spicelabs.saffron.fs.FileSystemMount;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.condition.EnabledIf;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HexFormat;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertTimeoutPreemptively;

/**
 * Corpus file verification tests.
 *
 * <p>These tests verify that the Saffron library can correctly read files
 * from VM images and compute matching SHA256 hashes.
 *
 * <p>The JSON verification files are GROUND TRUTH generated by EXTERNAL
 * filesystem tools (libguestfs in Docker), NOT by Saffron code. Any
 * discrepancy is a Saffron bug.
 *
 * <p><b>Zero tolerance:</b> Every sample file must be found and must have
 * exactly matching size and SHA256 hash.
 */
class CorpusFileVerificationTest {

    private static final String CORPUS_BASE = Path.of("test-corpus").toAbsolutePath().toString();
    private static final Gson GSON = new Gson();
    private static final Duration TEST_TIMEOUT = Duration.ofMinutes(5);
    private static List<CorpusTestData.CorpusImageData> corpusData;

    @BeforeAll
    static void loadCorpusData() throws IOException {
        corpusData = new ArrayList<>();

        Path verificationDir = Paths.get("src/test/resources/corpus-verification");
        if (!Files.isDirectory(verificationDir)) {
            return;
        }

        // Load all JSON files from the verification directory
        try (Stream<Path> files = Files.list(verificationDir)) {
            files.filter(p -> p.toString().endsWith(".json"))
                 .forEach(jsonPath -> {
                     try (InputStream is = Files.newInputStream(jsonPath)) {
                         CorpusTestData.CorpusImageData data = GSON.fromJson(new InputStreamReader(is), CorpusTestData.CorpusImageData.class);
                         if (data != null && data.imagePath != null && data.error == null) {
                             Path imagePath = resolveImagePath(data.imagePath);
                             if (imagePath != null && Files.exists(imagePath)) {
                                 corpusData.add(data);
                             }
                         }
                     } catch (Exception e) {
                         // Skip files that can't be loaded
                     }
                 });
        }
    }

    static boolean corpusExists() {
        return Files.isDirectory(Paths.get(CORPUS_BASE));
    }

    /**
     * Test that sample files can be found and have correct SHA256 hashes.
     *
     * <p>For each image, tests up to 5 sample files across all filesystems.
     * Every tested file must be found, have the correct size, and matching SHA256.
     */
    @TestFactory
    @EnabledIf("corpusExists")
    Collection<DynamicTest> testFileSha256OnImages() {
        List<DynamicTest> tests = new ArrayList<>();

        for (CorpusTestData.CorpusImageData data : corpusData) {
            Path imagePath = resolveImagePath(data.imagePath);
            if (imagePath == null || !Files.exists(imagePath)) continue;
            if (data.filesystems == null) continue;

            // Collect sample files from all filesystems
            List<CorpusTestData.SampleFile> allSamples = new ArrayList<>();
            for (CorpusTestData.FilesystemData fsData : data.filesystems) {
                if (fsData.sampleFiles != null) {
                    allSamples.addAll(fsData.sampleFiles);
                }
            }

            // Test up to 5 sample files per image
            int count = 0;
            for (CorpusTestData.SampleFile sampleFile : allSamples) {
                if (count >= 5) break;
                count++;

                tests.add(DynamicTest.dynamicTest(
                    "SHA256: " + data.imageBasename + ":" + truncatePath(sampleFile.path),
                    () -> assertTimeoutPreemptively(TEST_TIMEOUT,
                        () -> verifySha256(imagePath, data, sampleFile))
                ));
            }
        }

        return tests;
    }

    private String truncatePath(String path) {
        if (path == null) return "";
        if (path.length() <= 40) return path;
        return "..." + path.substring(path.length() - 37);
    }

    /**
     * Verify that a specific file exists and has the correct SHA256 hash.
     */
    private void verifySha256(Path imagePath, CorpusTestData.CorpusImageData data, CorpusTestData.SampleFile sampleFile) throws Exception {
        try (VirtualDisk disk = DiskReader.open(imagePath)) {
            // Mount all filesystems to find files across partitions and LVM volumes
            List<FileSystem> allFs = FileSystemMount.mountAll(disk);
            try {
                // Try to resolve the file across all mounted filesystems
                FileSystemEntry.RegularFile file = null;
                for (FileSystem fs : allFs) {
                    Optional<FileSystemEntry> entry = fs.resolve(sampleFile.path);
                    if (entry.isPresent() && entry.get() instanceof FileSystemEntry.RegularFile rf) {
                        file = rf;
                        break;
                    }
                }

                assertThat(file)
                    .as("File must exist: " + sampleFile.path + " in " + data.imageBasename)
                    .isNotNull();

                // Read file and compute SHA256
                byte[] content = file.readAllBytes();
                String actualSha256 = sha256(content);

                System.out.println(sampleFile.path + ": " + actualSha256.substring(0, 16) + "..." +
                                   " (size: " + content.length + " bytes)");

                // Verify size matches exactly
                assertThat(content.length)
                    .as("File size must match for " + sampleFile.path)
                    .isEqualTo(sampleFile.size);

                // Verify SHA256 matches exactly
                assertThat(actualSha256)
                    .as("SHA256 must match for " + sampleFile.path + " in " + data.imageBasename)
                    .isEqualTo(sampleFile.sha256.toLowerCase());
            } finally {
                for (FileSystem fs : allFs) {
                    try { fs.close(); } catch (Exception ignored) {}
                }
            }
        }
    }

    private String sha256(byte[] data) throws Exception {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(data);
        return HexFormat.of().formatHex(hash);
    }

    private static Path resolveImagePath(String containerPath) {
        if (containerPath != null && containerPath.startsWith("/corpus/")) {
            String relativePath = containerPath.substring("/corpus/".length());
            return Paths.get(CORPUS_BASE, relativePath);
        }
        return null;
    }
}
