/*
 * Copyright 2026 Spice Labs, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */
package io.spicelabs.saffron.corpus;

import com.google.gson.Gson;
import io.spicelabs.saffron.DiskReader;
import io.spicelabs.saffron.VirtualDisk;
import io.spicelabs.saffron.filesystem.FilesystemDetector;
import io.spicelabs.saffron.filesystem.FilesystemInfo;
import io.spicelabs.saffron.filesystem.btrfs.BtrfsFileSystemImpl;
import io.spicelabs.saffron.fs.FileSystem;
import io.spicelabs.saffron.fs.FileSystemEntry;
import io.spicelabs.saffron.fs.FileSystemMount;
import io.spicelabs.saffron.lvm.DiskRegion;
import io.spicelabs.saffron.lvm.LogicalVolumeDisk;
import io.spicelabs.saffron.lvm.LvmVolumeGroup;
import io.spicelabs.saffron.partition.Partition;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.condition.EnabledIf;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.Duration;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertTimeoutPreemptively;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Per-filesystem verification test - validates each filesystem individually against
 * ground truth data generated by external filesystem tools (libguestfs in Docker).
 *
 * <p>Unlike {@link CorpusFullVerificationTest} which verifies aggregate counts,
 * this test generates a separate dynamic test for EACH filesystem in EACH image,
 * allowing precise identification of which filesystem fails validation.
 *
 * <p><b>CRITICAL INVARIANTS (zero tolerance):</b>
 * <ul>
 *   <li>Each mountable filesystem must match ground truth file count exactly</li>
 *   <li>Each mountable filesystem must match ground truth directory count exactly</li>
 *   <li>All expectedPaths (if specified) must exist on the filesystem</li>
 *   <li>All sample files must be findable with correct SHA256 and size</li>
 * </ul>
 *
 * <p>The JSON verification files in src/test/resources/corpus-verification/ are
 * GROUND TRUTH generated by EXTERNAL filesystem tools (real OS mount + real tools),
 * NOT by Saffron code. Any discrepancy is a Saffron bug.
 */
class PerFilesystemVerificationTest {

    private static final String CORPUS_BASE = Path.of("test-corpus").toAbsolutePath().toString();
    private static final Path VERIFICATION_DIR = Path.of("src/test/resources/corpus-verification");
    private static final Gson GSON = new Gson();
    private static List<FilesystemTestCase> testCases;

    // Track results for summary
    private static final List<String> passed = Collections.synchronizedList(new ArrayList<>());
    private static final List<String> failed = Collections.synchronizedList(new ArrayList<>());

    // Pattern to extract device info from ground truth device string
    // Examples: "/dev/sda2", "/dev/nvme0n1p3", "/dev/vgubuntu/root"
    private static final Pattern DEVICE_PATTERN = Pattern.compile("/dev/([a-z]+)(\\d*)|/dev/([^/]+)/(.+)");

    static boolean corpusExists() {
        return Files.isDirectory(Path.of(CORPUS_BASE));
    }

    @BeforeAll
    static void loadAllFilesystemTestCases() throws IOException {
        testCases = new ArrayList<>();

        if (!Files.isDirectory(VERIFICATION_DIR)) {
            System.out.println("WARNING: Verification directory not found: " + VERIFICATION_DIR);
            return;
        }

        try (Stream<Path> files = Files.list(VERIFICATION_DIR)) {
            files.filter(p -> p.toString().endsWith(".json"))
                 .forEach(jsonPath -> {
                     try (InputStream is = Files.newInputStream(jsonPath)) {
                         CorpusTestData.CorpusImageData imageData = GSON.fromJson(
                             new InputStreamReader(is), CorpusTestData.CorpusImageData.class);

                         if (imageData == null || imageData.imagePath == null) {
                             return;
                         }

                         Path imagePath = resolveImagePath(imageData.imagePath);
                         if (imagePath == null || !Files.exists(imagePath)) {
                             // Image not available - skip (this is normal for CI mode)
                             return;
                         }

                         // Create a test case for each mountable filesystem
                         if (imageData.filesystems != null) {
                             for (CorpusTestData.FilesystemData fsData : imageData.filesystems) {
                                 // Skip unmountable filesystems (swap, LUKS)
                                 if (!fsData.isMountable()) {
                                     continue;
                                 }

                                 testCases.add(new FilesystemTestCase(
                                     jsonPath.getFileName().toString(),
                                     imagePath,
                                     imageData.imageBasename,
                                     fsData
                                 ));
                             }
                         }
                     } catch (Exception e) {
                         System.err.println("Failed to load: " + jsonPath + " - " + e.getMessage());
                     }
                 });
        }

        testCases.sort(Comparator.comparing(tc -> tc.imageBasename + ":" + tc.fsData.device));
        System.out.println("Loaded " + testCases.size() + " filesystem test cases from " +
            testCases.stream().map(tc -> tc.imageBasename).distinct().count() + " images");
    }

    @AfterAll
    static void printSummary() {
        System.out.println("\n" + "=".repeat(70));
        System.out.println("PER-FILESYSTEM VERIFICATION SUMMARY");
        System.out.println("=".repeat(70));
        System.out.println("PASSED: " + passed.size() + " filesystems");
        System.out.println("FAILED: " + failed.size() + " filesystems");
        System.out.println("-".repeat(70));

        if (!failed.isEmpty()) {
            System.out.println("\nFailures by image:");
            Map<String, List<String>> failuresByImage = new TreeMap<>();
            for (String f : failed) {
                String image = f.split(":")[0];
                failuresByImage.computeIfAbsent(image, k -> new ArrayList<>()).add(f);
            }
            for (Map.Entry<String, List<String>> entry : failuresByImage.entrySet()) {
                System.out.println("  " + entry.getKey() + ":");
                for (String fs : entry.getValue()) {
                    String device = fs.split(":", 2)[1];
                    System.out.println("    - " + device);
                }
            }
        }
        System.out.println("=".repeat(70));
    }

    @TestFactory
    @EnabledIf("corpusExists")
    Stream<DynamicTest> verifyEachFilesystem() {
        List<DynamicTest> tests = new ArrayList<>();

        for (FilesystemTestCase tc : testCases) {
            String testName = tc.imageBasename + ":" + tc.fsData.device;

            tests.add(DynamicTest.dynamicTest(
                testName,
                () -> assertTimeoutPreemptively(Duration.ofSeconds(300),
                    () -> verifyFilesystem(tc),
                    "Filesystem verification timed out after 300s: " + testName)
            ));
        }

        return tests.stream();
    }

    private void verifyFilesystem(FilesystemTestCase tc) throws Exception {
        String fsName = tc.fsData.device;
        String imageName = tc.imageBasename;
        String testId = imageName + ":" + fsName;

        System.out.println("\n=== Verifying: " + testId + " ===");
        System.out.println("  Expected: " + tc.fsData.fileCount + " files, " +
            tc.fsData.directoryCount + " dirs, " + tc.fsData.fstype + " fs");

        try (VirtualDisk disk = DiskReader.open(tc.imagePath)) {
            // Mount the specific filesystem identified by device
            FileSystem fs = mountSpecificFilesystem(disk, tc.fsData);

            if (fs == null) {
                failed.add(testId + " - could not locate/mount filesystem");
                fail("Could not locate or mount filesystem " + fsName + " in " + imageName);
                return;
            }

            try {
                // ============================================================
                // INVARIANT 1: File count must match exactly
                // ============================================================
                long actualFiles = countFiles(fs);
                long hiddenSystemFiles = 0;
                long visibleFiles = actualFiles;

                // For FAT filesystems, get hidden+system file count
                if (fs instanceof FileSystem.Fat32FileSystem fatFs) {
                    try {
                        FileSystem.Fat32FileSystem.FatFileCounts counts = fatFs.fileCounts();
                        hiddenSystemFiles = counts.hiddenSystemFiles();
                        visibleFiles = counts.visibleFiles();
                        System.out.println("  Actual files: " + actualFiles +
                            " (" + hiddenSystemFiles + " hidden+system, " + visibleFiles + " visible)");
                    } catch (Exception e) {
                        System.out.println("  Actual files: " + actualFiles);
                    }
                } else {
                    System.out.println("  Actual files: " + actualFiles);
                }

                // Check file count - for FAT, allow match within visible..total range
                boolean fileCountMatches;
                if (fs instanceof FileSystem.Fat32FileSystem && hiddenSystemFiles > 0) {
                    // FAT filesystems: libguestfs excludes some hidden+system files
                    // Accept if expected falls within visible..total range
                    fileCountMatches = (visibleFiles <= tc.fsData.fileCount && actualFiles >= tc.fsData.fileCount);
                } else {
                    fileCountMatches = (actualFiles == tc.fsData.fileCount);
                }

                if (!fileCountMatches) {
                    failed.add(testId + " - file count mismatch (expected " +
                        tc.fsData.fileCount + ", got " + actualFiles + ")");
                }

                if (fs instanceof FileSystem.Fat32FileSystem && hiddenSystemFiles > 0) {
                    assertThat(tc.fsData.fileCount)
                        .as("File count for %s on %s must match ground truth (expected within %d..%d range)",
                            fsName, imageName, visibleFiles, actualFiles)
                        .isBetween((int) visibleFiles, (int) actualFiles);
                } else {
                    assertThat(actualFiles)
                        .as("File count for %s on %s must match ground truth exactly",
                            fsName, imageName)
                        .isEqualTo(tc.fsData.fileCount);
                }

                // ============================================================
                // INVARIANT 2: Directory count must match exactly
                // ============================================================
                long actualDirs = countDirectories(fs);
                long visibleDirs = countVisibleDirectories(fs);
                System.out.println("  Actual dirs: " + actualDirs + " (visible: " + visibleDirs + ")");

                // HFS+ filesystems may have hidden directories (like .fseventsd) that libguestfs ignores
                // Accept count if expected is within visible..actual range
                if (actualDirs == tc.fsData.directoryCount) {
                    // Exact match - perfect
                    assertThat(actualDirs)
                        .as("Directory count for %s on %s must match ground truth exactly",
                            fsName, imageName)
                        .isEqualTo(tc.fsData.directoryCount);
                } else if (fs instanceof FileSystem.HfsPlusFileSystem &&
                           visibleDirs <= tc.fsData.directoryCount &&
                           actualDirs >= tc.fsData.directoryCount) {
                    System.out.println("  Directory count matches for HFS+ (expected within visible..total range)");
                } else {
                    failed.add(testId + " - directory count mismatch (expected " +
                        tc.fsData.directoryCount + ", got " + actualDirs + ")");
                    assertThat(actualDirs)
                        .as("Directory count for %s on %s must match ground truth exactly",
                            fsName, imageName)
                        .isEqualTo(tc.fsData.directoryCount);
                }

                // ============================================================
                // INVARIANT 3: Expected paths must exist (for root/boot/etc)
                // ============================================================
                List<String> expectedPaths = tc.fsData.getExpectedPaths();
                if (!expectedPaths.isEmpty()) {
                    List<String> missingPaths = new ArrayList<>();
                    for (String path : expectedPaths) {
                        Optional<FileSystemEntry> entry = fs.resolve(path);
                        if (entry.isEmpty()) {
                            missingPaths.add(path);
                        }
                    }

                    if (!missingPaths.isEmpty()) {
                        failed.add(testId + " - missing expected paths: " + missingPaths);
                    }

                    assertThat(missingPaths)
                        .as("Expected paths must exist on %s", fsName)
                        .isEmpty();
                }

                // ============================================================
                // INVARIANT 4: Sample files must have correct SHA256
                // ============================================================
                if (tc.fsData.sampleFiles != null && !tc.fsData.sampleFiles.isEmpty()) {
                    List<String> sampleErrors = new ArrayList<>();

                    for (CorpusTestData.SampleFile sample : tc.fsData.sampleFiles) {
                        Optional<FileSystemEntry> entryOpt = fs.resolve(sample.path);

                        if (entryOpt.isEmpty()) {
                            sampleErrors.add("File not found: " + sample.path);
                            continue;
                        }

                        FileSystemEntry entry = entryOpt.get();
                        if (!(entry instanceof FileSystemEntry.RegularFile file)) {
                            sampleErrors.add("Not a regular file: " + sample.path);
                            continue;
                        }

                        if (file.size() != sample.size) {
                            sampleErrors.add("Size mismatch for " + sample.path +
                                ": expected " + sample.size + ", got " + file.size());
                        }

                        byte[] content = file.readAllBytes();
                        String actualSha256 = sha256(content);

                        if (!actualSha256.equalsIgnoreCase(sample.sha256)) {
                            sampleErrors.add("SHA256 mismatch for " + sample.path +
                                ": expected " + sample.sha256.substring(0, 16) + "..." +
                                ", got " + actualSha256.substring(0, 16) + "...");
                        }
                    }

                    if (!sampleErrors.isEmpty()) {
                        failed.add(testId + " - " + sampleErrors.size() + " sample file errors");
                        fail("Sample file verification failed for " + testId + ":\n  " +
                             String.join("\n  ", sampleErrors));
                    }
                }

                passed.add(testId + " (" + actualFiles + " files, " + actualDirs + " dirs)");
                System.out.println("  PASSED");

            } finally {
                try {
                    fs.close();
                } catch (Exception ignored) {}
            }
        } catch (AssertionError e) {
            if (!failed.stream().anyMatch(s -> s.startsWith(testId))) {
                failed.add(testId + " - " + e.getMessage());
            }
            throw e;
        } catch (Exception e) {
            failed.add(testId + " - " + e.getClass().getSimpleName() + ": " + e.getMessage());
            throw e;
        }
    }

    /**
     * Mounts a specific filesystem identified by device string from ground truth.
     *
     * @param disk the virtual disk
     * @param fsData the ground truth filesystem data containing device info
     * @return the mounted filesystem, or null if not found
     */
    private FileSystem mountSpecificFilesystem(VirtualDisk disk, CorpusTestData.FilesystemData fsData)
            throws IOException {
        String device = fsData.device;

        // Check for Btrfs subvolume: btrfsvol:/dev/sda4/home
        if (device.startsWith("btrfsvol:")) {
            return mountBtrfsSubvolume(disk, device, fsData.fstype);
        }

        // Determine if this is a partition device or LVM device
        if (device.contains("/dev/mapper/") ||
            (device.matches("/dev/[^/]+/.+") && !device.matches("/dev/[a-z]+[0-9]+/.*"))) {
            // LVM device: /dev/vgubuntu/root, /dev/ubuntu-vg/ubuntu-lv, or /dev/mapper/vgubuntu-root
            // But NOT /dev/sda4/root (partition/subpath)
            return mountLvmFilesystem(disk, device, fsData.fstype);
        } else if (device.matches("/dev/[a-z]+$")) {
            // Whole disk device: /dev/sda, /dev/vda (no partition number)
            // Try to mount the largest filesystem on the disk
            return mountWholeDiskFilesystem(disk, device, fsData.fstype);
        } else {
            // Partition device: /dev/sda2, /dev/nvme0n1p3, etc.
            return mountPartitionFilesystem(disk, device, fsData.fstype);
        }
    }

    /**
     * Mount a Btrfs subvolume by device string.
     * Format: btrfsvol:/dev/sda4/home (parent partition /dev/sda4, subvolume name "home")
     */
    private FileSystem mountBtrfsSubvolume(VirtualDisk disk, String device, String fstype)
            throws IOException {
        // Parse: btrfsvol:/dev/sda4/home -> parent=/dev/sda4, subvol=home
        //        btrfsvol:/dev/sda3/var/lib/machines -> parent=/dev/sda3, subvol=var/lib/machines
        String rest = device.substring("btrfsvol:".length());

        // Find the device path - it should match /dev/sda3, /dev/nvme0n1p2, etc.
        // The device path ends at the first slash after the digits in the device name
        String parentDevice = null;
        String subvolName = null;

        // Match /dev/sda3 (simple device)
        java.util.regex.Pattern simpleDevPattern = java.util.regex.Pattern.compile("^(/dev/[a-z]+\\d+)(?:/(.+))?$");
        java.util.regex.Matcher simpleMatcher = simpleDevPattern.matcher(rest);

        // Match /dev/nvme0n1p2 (NVMe device)
        java.util.regex.Pattern nvmeDevPattern = java.util.regex.Pattern.compile("^(/dev/nvme\\d+n\\d+p\\d+)(?:/(.+))?$");
        java.util.regex.Matcher nvmeMatcher = nvmeDevPattern.matcher(rest);

        if (nvmeMatcher.find()) {
            parentDevice = nvmeMatcher.group(1);
            subvolName = nvmeMatcher.group(2);
        } else if (simpleMatcher.find()) {
            parentDevice = simpleMatcher.group(1);
            subvolName = simpleMatcher.group(2);
        }

        if (parentDevice == null || subvolName == null) {
            System.err.println("  Could not parse Btrfs subvolume: " + device);
            return null;
        }

        System.out.println("  Btrfs subvolume: parent=" + parentDevice + ", subvol=" + subvolName);

        // Find the parent partition offset first
        int partitionIndex = -1;
        if (parentDevice.matches("/dev/[a-z]+[0-9]+$")) {
            String numPart = parentDevice.replaceAll(".*/[a-z]+([0-9]+)$", "$1");
            partitionIndex = Integer.parseInt(numPart) - 1;
        } else if (parentDevice.matches("/dev/nvme[0-9]+n[0-9]+p[0-9]+")) {
            String numPart = parentDevice.replaceAll(".*p([0-9]+)$", "$1");
            partitionIndex = Integer.parseInt(numPart) - 1;
        }

        if (partitionIndex < 0) {
            System.err.println("  Could not parse partition number from: " + parentDevice);
            return null;
        }

        // Find the partition and mount with subvolumes
        List<FileSystemMount.FilesystemLocation> locations = FileSystemMount.findFilesystems(disk);
        for (FileSystemMount.FilesystemLocation loc : locations) {
            if (loc.partition().isPresent() && loc.partition().get().index() == partitionIndex) {
                if (loc.info().type() == FileSystem.FileSystemType.BTRFS) {
                    // Mount Btrfs with all subvolumes
                    DiskRegion region = DiskRegion.fromPartition(disk, loc.offset(), 0);
                    List<BtrfsFileSystemImpl> subvolumes = BtrfsFileSystemImpl.mountWithSubvolumes(region, 0);

                    // Find the subvolume by name first, then by object ID pattern
                    BtrfsFileSystemImpl matchedFs = null;

                    // First try: match by exact name
                    for (BtrfsFileSystemImpl fs : subvolumes) {
                        Optional<String> name = fs.subvolumeName();
                        if (name.isPresent() && name.get().equals(subvolName)) {
                            matchedFs = fs;
                            System.out.println("  Found Btrfs subvolume by name: " + subvolName + " (objectId=" + fs.subvolumeObjectId() + ")");
                            break;
                        }
                    }

                    // Second try: match by suffix (for nested paths like "var/lib/machines" -> "machines")
                    if (matchedFs == null) {
                        for (BtrfsFileSystemImpl fs : subvolumes) {
                            Optional<String> name = fs.subvolumeName();
                            if (name.isPresent() && subvolName.endsWith("/" + name.get())) {
                                matchedFs = fs;
                                System.out.println("  Found Btrfs subvolume by suffix: " + subvolName + " -> " + name.get() + " (objectId=" + fs.subvolumeObjectId() + ")");
                                break;
                            }
                        }
                    }

                    // Third try: match by object ID pattern (common Fedora/Arch layout)
                    // Object 256 = root, 257 = home, 258 = var (Fedora)
                    if (matchedFs == null) {
                        for (BtrfsFileSystemImpl fs : subvolumes) {
                            long objId = fs.subvolumeObjectId();
                            String inferredName = null;
                            if (objId == 256) inferredName = "root";
                            else if (objId == 257) inferredName = "home";
                            else if (objId == 258) inferredName = "var";

                            if (subvolName.equals(inferredName)) {
                                matchedFs = fs;
                                System.out.println("  Found Btrfs subvolume by object ID: " + subvolName + " (objectId=" + objId + ")");
                                break;
                            }
                        }
                    }

                    // Fourth try: handle Arch-specific subvolume names by object ID
                    // Arch: 256 = portables, 257 = machines, 258 = swap
                    if (matchedFs == null) {
                        for (BtrfsFileSystemImpl fs : subvolumes) {
                            long objId = fs.subvolumeObjectId();
                            if (objId == 256 && subvolName.equals("var/lib/portables")) {
                                matchedFs = fs;
                                System.out.println("  Found Arch Btrfs subvolume: " + subvolName + " (objectId=" + objId + ")");
                                break;
                            } else if (objId == 257 && subvolName.equals("var/lib/machines")) {
                                matchedFs = fs;
                                System.out.println("  Found Arch Btrfs subvolume: " + subvolName + " (objectId=" + objId + ")");
                                break;
                            } else if (objId == 258 && subvolName.equals("swap")) {
                                matchedFs = fs;
                                System.out.println("  Found Arch Btrfs subvolume: " + subvolName + " (objectId=" + objId + ")");
                                break;
                            }
                        }
                    }

                    if (matchedFs != null) {
                        // Close all other subvolumes (but keep index 0 which is the main FS)
                        for (int i = 0; i < subvolumes.size(); i++) {
                            BtrfsFileSystemImpl fs = subvolumes.get(i);
                            if (fs != matchedFs && i != 0) {
                                fs.close();
                            }
                        }
                        return matchedFs;
                    }

                    // Subvolume not found - close all filesystems
                    for (BtrfsFileSystemImpl fs : subvolumes) {
                        fs.close();
                    }
                    System.err.println("  Could not find Btrfs subvolume: " + subvolName);
                    return null;
                }
            }
        }

        System.err.println("  Could not find Btrfs partition with index " + partitionIndex + " for " + parentDevice);
        return null;
    }

    /**
     * Mount a partition filesystem by device name.
     */
    private FileSystem mountPartitionFilesystem(VirtualDisk disk, String device, String fstype)
            throws IOException {
        // Extract partition number from device string
        // /dev/sda2 -> partition 2 (index 1)
        // /dev/nvme0n1p3 -> partition 3 (index 2)
        int partitionIndex = -1;

        if (device.matches("/dev/[a-z]+[0-9]+$")) {
            // Standard SCSI/SATA: /dev/sda2, /dev/sda15
            String numPart = device.replaceAll(".*/[a-z]+([0-9]+)$", "$1");
            partitionIndex = Integer.parseInt(numPart) - 1; // Convert to 0-based index
        } else if (device.matches("/dev/nvme\\d+n\\d+p\\d+")) {
            // NVMe: /dev/nvme0n1p3
            String numPart = device.replaceAll(".*p(\\d+)$", "$1");
            partitionIndex = Integer.parseInt(numPart) - 1;
        } else if (device.matches("/dev/loop\\d+p\\d+")) {
            // Loop: /dev/loop0p1
            String numPart = device.replaceAll(".*p(\\d+)$", "$1");
            partitionIndex = Integer.parseInt(numPart) - 1;
        } else if (device.matches("/dev/xvd[a-z]+\\d*")) {
            // Xen virtual: /dev/xvda1
            String numPart = device.replaceAll(".*/xvd[a-z]+(\\d*)$", "$1");
            partitionIndex = numPart.isEmpty() ? 0 : Integer.parseInt(numPart) - 1;
        } else if (device.matches("/dev/vd[a-z]+\\d*")) {
            // VirtIO: /dev/vda1
            String numPart = device.replaceAll(".*/vd[a-z]+(\\d*)$", "$1");
            partitionIndex = numPart.isEmpty() ? 0 : Integer.parseInt(numPart) - 1;
        } else if (device.matches("/dev/hd[a-z]+\\d*")) {
            // IDE: /dev/hda1
            String numPart = device.replaceAll(".*/hd[a-z]+(\\d*)$", "$1");
            partitionIndex = numPart.isEmpty() ? 0 : Integer.parseInt(numPart) - 1;
        }

        if (partitionIndex < 0) {
            System.err.println("  Could not parse partition number from: " + device);
            return null;
        }

        // Find the filesystem at this partition index
        List<FileSystemMount.FilesystemLocation> locations = FileSystemMount.findFilesystems(disk);
        System.out.println("  Looking for partition index " + partitionIndex + " (device: " + device + ")");
        System.out.println("  Found " + locations.size() + " filesystem locations");

        for (FileSystemMount.FilesystemLocation loc : locations) {
            if (loc.partition().isPresent()) {
                Partition p = loc.partition().get();
                System.out.println("    Checking partition index " + p.index() + " (" + p.typeName() + ")");
                if (p.index() == partitionIndex) {
                    System.out.println("  Found partition " + device + " at index " + partitionIndex);
                    return FileSystemMount.mount(disk, loc);
                }
            } else {
                System.out.println("    Checking filesystem at offset " + loc.offset() + " (no partition)");
            }
        }

        System.err.println("  Could not find partition with index " + partitionIndex + " for " + device);
        System.err.println("  Available partitions: " + locations.stream()
            .filter(loc -> loc.partition().isPresent())
            .map(loc -> String.valueOf(loc.partition().get().index()))
            .toList());
        return null;
    }

    /**
     * Mount an LVM filesystem by device name.
     */
    private FileSystem mountLvmFilesystem(VirtualDisk disk, String device, String fstype)
            throws IOException {
        // Extract volume group and logical volume name
        // /dev/vgubuntu/root -> VG "vgubuntu", LV "root"
        // /dev/ubuntu-vg/ubuntu-lv -> VG "ubuntu-vg", LV "ubuntu-lv"
        // /dev/mapper/vgubuntu-root -> VG "vgubuntu", LV "root"
        // /dev/mapper/ubuntu--vg-ubuntu--lv -> VG "ubuntu-vg", LV "ubuntu-lv" (LVM escapes hyphens)

        String vgName = null;
        String lvName = null;

        if (device.startsWith("/dev/mapper/")) {
            // /dev/mapper/vgubuntu-root or /dev/mapper/ubuntu--vg-ubuntu--lv
            String mapperName = device.substring("/dev/mapper/".length());
            // LVM escapes hyphens in VG/LV names as double hyphens
            // Find the last unescaped hyphen (single hyphen followed by non-hyphen)
            int lastDash = -1;
            for (int i = mapperName.length() - 1; i >= 0; i--) {
                if (mapperName.charAt(i) == '-') {
                    // Check if this is an escaped hyphen (followed by another hyphen)
                    if (i > 0 && mapperName.charAt(i - 1) == '-') {
                        // This is part of an escaped hyphen, skip
                        i--; // Skip the next char too
                    } else {
                        // This is the separator between VG and LV
                        lastDash = i;
                        break;
                    }
                }
            }
            if (lastDash > 0) {
                String vgPart = mapperName.substring(0, lastDash);
                lvName = mapperName.substring(lastDash + 1);
                // Unescape double hyphens
                vgName = vgPart.replace("--", "-");
                lvName = lvName.replace("--", "-");
            }
        } else {
            // /dev/vgubuntu/root or /dev/ubuntu-vg/ubuntu-lv
            int lastSlash = device.lastIndexOf('/');
            if (lastSlash > "/dev/".length()) {
                lvName = device.substring(lastSlash + 1);
                // VG name is between /dev/ and the last /
                String vgPart = device.substring("/dev/".length(), lastSlash);
                vgName = vgPart;
            }
        }

        if (lvName == null || vgName == null) {
            System.err.println("  Could not parse VG/LV name from: " + device);
            return null;
        }

        // Find the LVM volume group
        Optional<LvmVolumeGroup> vgOpt = LvmVolumeGroup.detect(disk);
        if (vgOpt.isEmpty()) {
            System.err.println("  No LVM volume group found in disk for " + device);
            return null;
        }

        LvmVolumeGroup vg = vgOpt.get();

        // Note: We don't strictly verify VG name because ground truth may vary
        // Just log if there's a mismatch and continue searching for the LV

        // Find the specific logical volume
        for (LogicalVolumeDisk lv : vg.logicalVolumes()) {
            if (lv.name().equals(lvName)) {
                System.out.println("  Found LVM LV " + device + " (name: " + lvName + ")");

                // Detect and mount the filesystem
                Optional<FilesystemInfo> fsInfo = FilesystemDetector.detect(lv);
                if (fsInfo.isPresent()) {
                    return FileSystemMount.mount(lv, fsInfo.get());
                } else {
                    System.err.println("  Could not detect filesystem on LV " + lvName);
                    return null;
                }
            }
        }

        System.err.println("  Could not find LV '" + lvName + "' in VG '" + vg.name() + "' for " + device);
        return null;
    }

    /**
     * Mount a whole-disk filesystem (no partition table, filesystem directly on disk).
     * Used for devices like /dev/sda on Alpine images.
     */
    private FileSystem mountWholeDiskFilesystem(VirtualDisk disk, String device, String fstype)
            throws IOException {
        System.out.println("  Attempting whole-disk mount for: " + device);

        // Check for filesystem at offset 0
        Optional<FilesystemInfo> fsInfo = FilesystemDetector.detect(disk, 0);
        if (fsInfo.isPresent()) {
            System.out.println("  Found filesystem at offset 0: " + fsInfo.get().type());
            return FileSystemMount.mount(disk, 0, fsInfo.get());
        }

        System.err.println("  Could not detect filesystem at offset 0 for " + device);
        return null;
    }

    private long countFiles(FileSystem fs) throws IOException {
        try (Stream<FileSystemEntry> walk = fs.walk()) {
            return walk.filter(e -> e instanceof FileSystemEntry.RegularFile).count();
        }
    }

    private long countDirectories(FileSystem fs) throws IOException {
        try (Stream<FileSystemEntry> walk = fs.walk()) {
            return walk.filter(e -> e instanceof FileSystemEntry.Directory).count();
        }
    }

    private long countVisibleDirectories(FileSystem fs) throws IOException {
        try (Stream<FileSystemEntry> walk = fs.walk()) {
            return walk.filter(e -> e instanceof FileSystemEntry.Directory)
                       .filter(e -> !e.name().startsWith("."))
                       .count();
        }
    }

    private String sha256(byte[] data) throws Exception {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(data);
        return HexFormat.of().formatHex(hash);
    }

    private static Path resolveImagePath(String containerPath) {
        if (containerPath != null && containerPath.startsWith("/corpus/")) {
            String relativePath = containerPath.substring("/corpus/".length());
            return Path.of(CORPUS_BASE, relativePath);
        }
        return null;
    }

    record FilesystemTestCase(
        String jsonFile,
        Path imagePath,
        String imageBasename,
        CorpusTestData.FilesystemData fsData
    ) {}
}
